FROM mklee03/hpc_stack:9.4.0

ARG fms_version=main

ENV FMS_ROOT=/FMS/gcc/9.4.0

RUN git clone https://github.com/NOAA-GFDL/FMS.git FMS/src \
  && cd FMS/src && git checkout $fms_version \
  && echo `git log -n 1`                     \
  && export NetCDF_ROOT=`nc-config --prefix` \
  && cmake -DCMAKE_INSTALL_PREFIX=$FMS_ROOT -DOPENMP=ON -D32BIT=ON -D64BIT=ON -DGFS_PHYS=ON . \
  && make install

FROM mklee03/hpc_stack:9.4.0
COPY --from=0 /FMS /FMS