FROM _UBUNTU_TAG_ #: mkl/ubuntu_gcc:20.04_10.1

#: TAKEN FROM
#: https://github.com/spack/spack/blob/develop/share/spack/docker/ubuntu-1804.dockerfile

ENV SPACK_ROOT=/opt/spack
ENV SPACK_VER=_SPACK_VER_
ENV DEBIAN_FRONTEND=noninteractive
#: SPACK_VER=releases/v0.16

RUN apt-get -yqq update && apt-get -yqq install --no-install-recommends \
        build-essential \
        ca-certificates \
        curl      \
        file      \
        git       \
        gnupg2    \
        iproute2  \
        lmod      \
        locales   \
        lua-posix \
        python3   \
        python3-pip        \
        python3-setuptools \
        tcl                \
        unzip              \
 && locale-gen en_US.UTF-8 \
 && pip3 install boto3

RUN cd /opt  && git clone https://github.com/spack/spack && \
    cd spack && git checkout $SPACK_VER && cd

RUN mkdir -p $SPACK_ROOT/opt/spack

RUN ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash \
          /usr/local/bin/docker-shell                    \
 && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash \
          /usr/local/bin/interactive-shell               \
 && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash \
          /usr/local/bin/spack-env

# Add LANG default to en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN mkdir -p /root/.spack \
 && cp $SPACK_ROOT/share/spack/docker/modules.yaml \
        /root/.spack/modules.yaml \
 && rm -rf /root/*.* /run/nologin $SPACK_ROOT/.git

# [WORKAROUND]
# https://superuser.com/questions/1241548/
#     xubuntu-16-04-ttyname-failed-inappropriate-ioctl-for-device#1253889
RUN [ -f ~/.profile ]                                               \
 && sed -i 's/mesg n/( tty -s \&\& mesg n || true )/g' ~/.profile \
 || true

# [WORKAROUND]
# https://bugs.launchpad.net/ubuntu/+source/lua-posix/+bug/1752082
RUN ln -s posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.2/posix.so

WORKDIR /root
SHELL ["docker-shell"]

# TODO: add a command to Spack that (re)creates the package cache
#RUN spack spec hdf5+mpi

ENTRYPOINT ["/bin/bash", "/opt/spack/share/spack/docker/entrypoint.bash"]
CMD ["interactive-shell"]
