FROM mklee03/fms:2020.04.03

WORKDIR /ufs-weather-model

COPY *.sh .

RUN git clone --recursive --branch develop https://github.com/ufs-community/ufs-weather-model.git src

# control
RUN ./setup_control.sh

#RUN export CMAKE_FLAGS="-D32BIT=ON -DMULTI_GASES=OFF -DCMAKE_BUILD_TYPE=Release" \
# && export CCPP_SUITES="FV3_GFS_v16" \
# && export CMAKE_FLAGS="${CMAKE_FLAGS} -DAPP=ATM" \
# && src/build.sh && mv src/build/ufs_model ufs-weather-model/control.exe \
# && rm -rf src/build

# coupled
#RUN export CMAKE_FLAGS="-DMULTI_GASES=OFF -DCMAKE_BUILD_TYPE=Release" \
# && export CCPP_SUITES="FV3_GFS_2017_coupled,FV3_GFS_v15p2_coupled,FV3_GFS_v16_coupled,FV3_GFS_v16_couplednsst" \
# && export CMAKE_FLAGS="${CMAKE_FLAGS} -DAPP=S2S" \
# && src/build.sh && mv src/build/ufs_model ufs-weather-model/cpld.exe \
# && rm -rf src/build

# regional
#RUN export CMAKE_FLAGS="-D32BIT=ON -DMULTI_GASES=OFF -DCMAKE_BUILD_TYPE=Release" \
# && export CCPP_SUITES="FV3_GFS_v15_thompson_mynn,FV3_GFS_v15_thompson_mynn_RRTMGP" \
# && export CMAKE_FLAGS="${CMAKE_FLAGS} -DAPP=ATM" \
# && src/build.sh && mv src/build/ufs_model ufs-weather-model/regional.exe \
# && rm -rf src/build


ENTRYPOINT [ "/bin/bash" ]
