name: build_ubuntu

on:
  push:
    branches:
      - ubuntu_docker

env:
  DOCKER_TAG: 9.4.0

jobs:
  build_ubuntu_container:
    runs-on:  ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker_build
        run: |
          docker build -f ./Dockerfile_ubuntu -t mklee03/gcc:${{env.DOCKER_TAG}} .
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          docker push mklee03/gcc:${{env.DOCKER_TAG}}

      - name: docker_test
        run: docker run mklee03/gcc:${{env.DOCKER_TAG}} -c "gcc --version"
